# Generated by Django 4.0.4 on 2022-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_units_count_alter_building_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='units_count',
            field=models.IntegerField(),
        ),
    ]
