# Generated by Django 4.0.4 on 2022-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_tag_review_building_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='tenants',
            field=models.ManyToManyField(to='buildings.tenant'),
        ),
    ]
