# Generated by Django 4.0.4 on 2022-04-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_alter_building_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
            preserve_default=False,
        ),
    ]
