# Generated by Django 4.0.4 on 2022-04-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_review_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
